spring:
  application:
    name: api-collaboration-platform
  datasource:
    url: jdbc:mariadb://localhost:3306/apicollab?createDatabaseIfNotExist=true
    username: root
    password: "260190"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'validate' or 'none' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  
server:
  port: 8080
